import type { ModuleId } from './loadout'

export interface Vec2 {
  readonly x: number
  readonly y: number
}

/** Live ability state for one tank (all zero when nothing is active). */
export interface TankEffects {
  /** Damage absorption remaining while the shield is up. */
  readonly shieldHp: number
  /** Ticks of shield uptime remaining. */
  readonly shieldTicks: number
  /** Ticks of afterburner speed remaining. */
  readonly boostTicks: number
  /** Ticks of post-boost fatigue remaining. */
  readonly fatigueTicks: number
  readonly pingCooldown: number
  readonly shieldCooldown: number
  readonly boostCooldown: number
}

export const IDLE_EFFECTS: TankEffects = {
  shieldHp: 0,
  shieldTicks: 0,
  boostTicks: 0,
  fatigueTicks: 0,
  pingCooldown: 0,
  shieldCooldown: 0,
  boostCooldown: 0,
}

export interface Rect {
  readonly x: number
  readonly y: number
  readonly width: number
  readonly height: number
}

export interface ArenaState {
  readonly width: number
  readonly height: number
  readonly obstacles: ReadonlyArray<Rect>
}

export interface TankState {
  readonly id: number
  readonly name: string
  /** Team number, or null for a solo tank. */
  readonly team: number | null
  readonly x: number
  readonly y: number
  /** Hull heading in radians, world coordinates. */
  readonly heading: number
  /** Turret heading in radians, world coordinates. */
  readonly turretHeading: number
  /** Current signed speed in px/s (negative = reversing). */
  readonly speed: number
  readonly hp: number
  /** Ticks until the cannon can fire again. */
  readonly cooldown: number
  readonly alive: boolean
  /** True if the tank tried to move last tick but was obstructed. */
  readonly blocked: boolean
  /** Sensor arc in radians; range scales inversely (see config.sensorRange). */
  readonly sensorArc: number
  /** Modules this tank bought with its loadout points. */
  readonly modules: ReadonlyArray<ModuleId>
  /** Live ability state. */
  readonly fx: TankEffects
}

export interface ShellState {
  readonly id: number
  readonly ownerId: number
  readonly x: number
  readonly y: number
  readonly heading: number
  /** Fire power 1..3; damage and speed derive from it. */
  readonly power: number
}

export type CollisionKind = 'wall' | 'obstacle' | 'tank'

export interface HitByShellEvent {
  readonly damage: number
  /** Bearing of the impact relative to the hull heading, radians. */
  readonly bearing: number
}

export interface CollisionEvent {
  readonly kind: CollisionKind
  readonly bearing: number
}

export interface PingContact {
  readonly id: number
  readonly x: number
  readonly y: number
  readonly heading: number
  readonly speed: number
}

export interface TankEvents {
  readonly hitByShell: ReadonlyArray<HitByShellEvent>
  readonly shellHitEnemy: ReadonlyArray<{ readonly targetId: number }>
  readonly collisions: ReadonlyArray<CollisionEvent>
  readonly enemiesDestroyed: ReadonlyArray<{ readonly id: number }>
  /** Someone fired a radar ping from this position (everyone hears it). */
  readonly pinged: ReadonlyArray<Vec2>
  /** This tank's own radar ping results: every living tank, ignoring LOS. */
  readonly pingResults: ReadonlyArray<PingContact>
}

export interface SimState {
  readonly tick: number
  readonly arena: ArenaState
  readonly tanks: ReadonlyArray<TankState>
  readonly shells: ReadonlyArray<ShellState>
  readonly nextShellId: number
  /** Events generated by the most recent step, indexed by tank id. */
  readonly events: ReadonlyArray<TankEvents>
}

export type TurnCommand =
  | { readonly kind: 'rate'; readonly value: number }
  | { readonly kind: 'to'; readonly target: number }

/** Persistent movement intents plus the one-shot fire power for one tank. */
export interface TankIntents {
  readonly drive: number
  readonly turn: TurnCommand
  readonly turretTurn: TurnCommand
  /** 0 = hold fire; otherwise fire power 1..3 (one-shot, reset every tick). */
  readonly fire: number
  /** Desired sensor arc in radians (persistent). */
  readonly sensorArc: number
  /** One-shot ability triggers (no-ops without the matching module). */
  readonly ping: boolean
  readonly shield: boolean
  readonly boost: boolean
}

export const IDLE_INTENTS: TankIntents = {
  drive: 0,
  turn: { kind: 'rate', value: 0 },
  turretTurn: { kind: 'rate', value: 0 },
  fire: 0,
  sensorArc: Math.PI / 2,
  ping: false,
  shield: false,
  boost: false,
}

export interface TankDetection {
  readonly id: number
  readonly distance: number
  /** Bearing relative to the sensing turret's heading, radians. */
  readonly bearing: number
  readonly heading: number
  readonly speed: number
}

export interface ObstacleDetection {
  readonly distance: number
  readonly bearing: number
  readonly rect: Rect
}

export interface WallDetection {
  readonly distance: number
  readonly bearing: number
}

export interface SensorReading {
  readonly tanks: ReadonlyArray<TankDetection>
  readonly obstacles: ReadonlyArray<ObstacleDetection>
  readonly wall: WallDetection | null
}
