export interface Vec2 {
  readonly x: number
  readonly y: number
}

export interface Rect {
  readonly x: number
  readonly y: number
  readonly width: number
  readonly height: number
}

export interface ArenaState {
  readonly width: number
  readonly height: number
  readonly obstacles: ReadonlyArray<Rect>
}

export interface TankState {
  readonly id: number
  readonly name: string
  readonly x: number
  readonly y: number
  /** Hull heading in radians, world coordinates. */
  readonly heading: number
  /** Turret heading in radians, world coordinates. */
  readonly turretHeading: number
  /** Current signed speed in px/s (negative = reversing). */
  readonly speed: number
  readonly hp: number
  /** Ticks until the cannon can fire again. */
  readonly cooldown: number
  readonly alive: boolean
  /** True if the tank tried to move last tick but was obstructed. */
  readonly blocked: boolean
}

export interface ShellState {
  readonly id: number
  readonly ownerId: number
  readonly x: number
  readonly y: number
  readonly heading: number
}

export type CollisionKind = 'wall' | 'obstacle' | 'tank'

export interface HitByShellEvent {
  readonly damage: number
  /** Bearing of the impact relative to the hull heading, radians. */
  readonly bearing: number
}

export interface CollisionEvent {
  readonly kind: CollisionKind
  readonly bearing: number
}

export interface TankEvents {
  readonly hitByShell: ReadonlyArray<HitByShellEvent>
  readonly shellHitEnemy: ReadonlyArray<{ readonly targetId: number }>
  readonly collisions: ReadonlyArray<CollisionEvent>
  readonly enemiesDestroyed: ReadonlyArray<{ readonly id: number }>
}

export interface SimState {
  readonly tick: number
  readonly arena: ArenaState
  readonly tanks: ReadonlyArray<TankState>
  readonly shells: ReadonlyArray<ShellState>
  readonly nextShellId: number
  /** Events generated by the most recent step, indexed by tank id. */
  readonly events: ReadonlyArray<TankEvents>
}

export type TurnCommand =
  | { readonly kind: 'rate'; readonly value: number }
  | { readonly kind: 'to'; readonly target: number }

/** Persistent movement intents plus the one-shot fire flag for one tank. */
export interface TankIntents {
  readonly drive: number
  readonly turn: TurnCommand
  readonly turretTurn: TurnCommand
  readonly fire: boolean
}

export const IDLE_INTENTS: TankIntents = {
  drive: 0,
  turn: { kind: 'rate', value: 0 },
  turretTurn: { kind: 'rate', value: 0 },
  fire: false,
}

export interface TankDetection {
  readonly id: number
  readonly distance: number
  /** Bearing relative to the sensing turret's heading, radians. */
  readonly bearing: number
  readonly heading: number
  readonly speed: number
}

export interface ObstacleDetection {
  readonly distance: number
  readonly bearing: number
  readonly rect: Rect
}

export interface WallDetection {
  readonly distance: number
  readonly bearing: number
}

export interface SensorReading {
  readonly tanks: ReadonlyArray<TankDetection>
  readonly obstacles: ReadonlyArray<ObstacleDetection>
  readonly wall: WallDetection | null
}
